FROM node:20-slim

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

# NEXT_PUBLIC_* vars must be baked into the client bundle at build time.
# Pass these via --build-arg during docker build. Do NOT put them in .env.production.
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_SOCKET_URL
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_GHL_API_BASE_URL
ARG NEXT_PUBLIC_GHL_LOCATION_ID
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_GHL_API_BASE_URL=$NEXT_PUBLIC_GHL_API_BASE_URL
ENV NEXT_PUBLIC_GHL_LOCATION_ID=$NEXT_PUBLIC_GHL_LOCATION_ID

RUN npm run build

EXPOSE 4004

ENV NODE_ENV=production
ENV NODE_OPTIONS="--max-old-space-size=4096"

CMD ["node", "server.prod.js"]
